### ISSUE TITLE
粘贴后直接变成很长一串base64了，虽然可以看到图片

### ISSUE THREAD

**Issue by alinecode** [yifengyou/markdown-image-paste-delete#1]

**Comment by yifengyou** [comment]
咦，，怎么会这样？请问你是选中文本区域后，粘贴的，还是没有勾选任何区域粘贴的？还是。是win平台还是其他平台？

**Comment by yifengyou** [comment]
> _No description provided._

咦，，怎么会这样？请问你是选中文本区域后，粘贴的，还是没有勾选任何区域粘贴的？还是。是win平台还是其他平台？

**Comment by yifengyou** [comment]
> _No description provided._

咦。。我测试没遇到过酱紫问题。
请问你是选中文本区域后，粘贴的，还是没有勾选任何区域粘贴的？
win平台还是其他平台？
可以提供截图吗？

**Comment by yifengyou** [comment]
> _No description provided._

你好，麻烦反馈一下详细错误信息，我这边好修改。

**Comment by alinecode** [comment]
> > _No description provided._
> 
> 你好，麻烦反馈一下详细错误信息，我这边好修改。

选中的，win平台，截图稍后

**Comment by alinecode** [comment]
选中的，win10，截图稍后

**Comment by alinecode** [comment]
> > _No description provided._
> 
> 你好，麻烦反馈一下详细错误信息，我这边好修改。

![image](https://user-images.githubusercontent.com/37790048/63483339-a5792d80-c4ce-11e9-8867-2b02a2ef4d41.png)

![image](https://user-images.githubusercontent.com/37790048/63483382-ca6da080-c4ce-11e9-8790-9a6d255acfd8.png)

**Comment by alinecode** [comment]
> > _No description provided._
> 
> 你好，麻烦反馈一下详细错误信息，我这边好修改。

用的tim的截图，atom版本1.38.2

![image](https://user-images.githubusercontent.com/37790048/63483501-318b5500-c4cf-11e9-88c0-e0221d77caca.png)

![image](https://user-images.githubusercontent.com/37790048/63483580-77481d80-c4cf-11e9-83a1-9744a66de472.png)

**Comment by alinecode** [comment]
> > > _No description provided._
> > 
> > 
> > 你好，麻烦反馈一下详细错误信息，我这边好修改。
> 
> 用的tim的截图，atom版本1.38.2
> 
> ![image](https://user-images.githubusercontent.com/37790048/63483501-318b5500-c4cf-11e9-88c0-e0221d77caca.png)
> 
> ![image](https://user-images.githubusercontent.com/37790048/63483580-77481d80-c4cf-11e9-83a1-9744a66de472.png)

选中的空行

**Comment by yifengyou** [comment]
![image](https://user-images.githubusercontent.com/19882390/63826871-a9f08b00-c993-11e9-862b-603a369157e3.png)
![image](https://user-images.githubusercontent.com/19882390/63826877-b1179900-c993-11e9-9c13-971cbac425cb.png)
Atom版本不一样，然后我用的QQ。。。容我装个TIM和Atom 1.38.2x64试试

话说你怎么closed

**Comment by alinecode** [comment]
> ![image](https://user-images.githubusercontent.com/19882390/63826871-a9f08b00-c993-11e9-862b-603a369157e3.png)
> ![image](https://user-images.githubusercontent.com/19882390/63826877-b1179900-c993-11e9-9c13-971cbac425cb.png)
> Atom版本不一样，然后我用的QQ。。。容我装个TIM和Atom 1.38.2x64试试
> 
> 话说你怎么closed
点错...

**Comment by yifengyou** [comment]
> 选中的，win10，截图稍后

你好，命名贴图限定了选定字符范围
          # 检测选中区域是否可以构成文件名
          filenamePattern = /// ^[0-9a-zA-Z-_]+$ ///
0-9，a-z，A-z，-_ 
不符合的直接快速贴图。
然后，我这装了TIM以及对应的Atom版本，无法重现你说的问题。如果你方便的话，麻烦添加QQ 842056007 ，远程查看一下。谢谢~

![image](https://user-images.githubusercontent.com/19882390/63833009-8f72dd80-c9a4-11e9-8575-4b9c73709ff6.png)
![image](https://user-images.githubusercontent.com/19882390/63833052-a285ad80-c9a4-11e9-94b5-1c19f55fc11c.png)

**Comment by alinecode** [comment]
> > 选中的，win10，截图稍后
> 
> 你好，命名贴图限定了选定字符范围
> # 检测选中区域是否可以构成文件名
> filenamePattern = /// ^[0-9a-zA-Z-_]+$ /// 0-9，a-z，A-z，-_
> 不符合的直接快速贴图。
> 然后，我这装了TIM以及对应的Atom版本，无法重现你说的问题。如果你方便的话，麻烦添加QQ 842056007 ，远程查看一下。谢谢~
> 
> ![image](https://user-images.githubusercontent.com/19882390/63833009-8f72dd80-c9a4-11e9-8575-4b9c73709ff6.png)
> ![image](https://user-images.githubusercontent.com/19882390/63833052-a285ad80-c9a4-11e9-94b5-1c19f55fc11c.png)

那有可能是文件名判断的问题了吧！我的电脑的截图生成的文件名包含的字符好像有点多，不知道是不是这个：
![image](https://user-images.githubusercontent.com/37790048/63904803-d0baca00-ca44-11e9-9e8c-4950cc72f551.png)

我在设置中换了个存储路径（路径中不包含特殊字符），选择不保存到默认目录下，图片也是直接变很长一串了。
然后我又换了个目录中不含特殊字符的项目，选择保存到默认目录下，还是这个问题。
我想可以直接把文件名给重置成时间试试...

另外，能否这样处理图片呢：粘贴图片后，直接上传到github的仓库内，好像只需要github的token值就行，就像小书匠的github图床一样：
![image](https://user-images.githubusercontent.com/37790048/63905216-2479e300-ca46-11e9-89ca-2635006ae1f4.png)
🤞

可能只有周末方便远程...

**Comment by yifengyou** [comment]
> > > 选中的，win10，截图稍后
> > 
> > 
> > 你好，命名贴图限定了选定字符范围
> > # 检测选中区域是否可以构成文件名
> > filenamePattern = /// ^[0-9a-zA-Z-_]+$ /// 0-9，a-z，A-z，-_
> > 不符合的直接快速贴图。
> > 然后，我这装了TIM以及对应的Atom版本，无法重现你说的问题。如果你方便的话，麻烦添加QQ 842056007 ，远程查看一下。谢谢~
> > ![image](https://user-images.githubusercontent.com/19882390/63833009-8f72dd80-c9a4-11e9-8575-4b9c73709ff6.png)
> > ![image](https://user-images.githubusercontent.com/19882390/63833052-a285ad80-c9a4-11e9-94b5-1c19f55fc11c.png)
> 
> 那有可能是文件名判断的问题了吧！我的电脑的截图生成的文件名包含的字符好像有点多，不知道是不是这个：
> ![image](https://user-images.githubusercontent.com/37790048/63904803-d0baca00-ca44-11e9-9e8c-4950cc72f551.png)
> 
> 我在设置中换了个存储路径（路径中不包含特殊字符），选择不保存到默认目录下，图片也是直接变很长一串了。
> 然后我又换了个目录中不含特殊字符的项目，选择保存到默认目录下，还是这个问题。
> 我想可以直接把文件名给重置成时间试试...
> 
> 另外，能否这样处理图片呢：粘贴图片后，直接上传到github的仓库内，好像只需要github的token值就行，就像小书匠的github图床一样：
> ![image](https://user-images.githubusercontent.com/37790048/63905216-2479e300-ca46-11e9-89ca-2635006ae1f4.png)
> 🤞
> 
> 可能只有周末方便远程...

%[]都没有加到文件名中呢。。但是文件名也不够成原因。不符合规则直接快速贴图的。
另外你的需求，粘贴图片后，直接上传到github的仓库内。可以搞成。但是我这个插件主要用于本地暂时。我个人写作习惯是本地md编辑再push github。本地化的话一方面离线查看，一份clone到处能看，另一方面维护起来也方便极了。。。这个插件就尽可能简单点儿呗。
